name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "17"
      - name: Install modules
        run: npm ci
      - name: ESLint
        run: npx eslint --ext .js --ext .ts .
      - name: TypeScript validity
        run: npm run test:typescript
      - name: Coverage
        run: npx c8 mocha
